spring.application.name=demo

server.port=${PORT:4040}


spring.jpa.open-in-view=false


spring.datasource.url=jdbc:postgresql://orchid-tarsier-14148.jxf.gcp-asia-south1.cockroachlabs.cloud:26257/aems_db?sslmode=require
spring.datasource.username=aemsdb_user40
spring.datasource.password=2OwSS03uiLJ-9cN52jLG_A

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000